with-expecter: true
dir: "mocks"
outpkg: "mocks"
mockname: "{{.InterfaceNameCamel}}"
filename: "{{.InterfaceNameSnake}}_mock.go"
packages:
  github.com/cronnoss/tickets-api/internal/app/transport/httpserver:
    interfaces:
      ShowService:
      EventService:
      PlaceService:

